name: Auto Release Tag
on: 
  pull_request:
    branches: 
      - master
    types:
      - closed
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Get branch name based on PR
      uses: andrevalentin/get-branch-name-by-pr@master
      id: pr_data
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        pr-id: ${{ github.event.pull_request.number }}
        
    - name: Print branch name
      run: |
        echo "This is PR from branch ${{ steps.pr_data.outputs.branch }}"
    
    - name: Get and check if branch name is an `release/*`
      uses: uynguyen-wonderlabs/get-branch-name-github-action@master
      id: get-branch
      with:
        branch: ${{ steps.pr_data.outputs.branch }}
        
    - name: Check and get release version only
      if: ${{ steps.get-branch.outputs.is_release_branch == 'YES' }}
      id: get-version
      run: |
        version=$(echo ${{ steps.get-branch.outputs.branch }} | sed -e "s/release\///g")
        echo "::set-output name=release_version::${version}"
        echo ${version}
        
    - name: Print branch name
      run: |
        echo "The branch ${{ steps.pr_data.outputs.branch }} is used for checking"
        echo "This branch has is_release_branch = ${{ steps.get-branch.outputs.is_release_branch }}"
        echo "This branch has release_version = ${{ steps.get-version.outputs.release_version }}"
      
    - name: Create Release tag
      if: ${{ steps.get-branch.outputs.is_release_branch == 'YES' }}
      id: create_release
      uses: actions/create-release@v1
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
      with:
          tag_name: v${{ steps.get-version.outputs.release_version }}
          release_name: Release ${{ steps.get-version.outputs.release_version }}
          commitish: master
          body: |
            Changes in this Release
            - First Change
            - Second Change
          draft: false
          prerelease: false
