name: Auto PR
on:
  push:
    branches:
      - release/2.0.0
jobs:
  AutoPR:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{github.ref}}
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        id: create_pr
        with:
          branch: ${{github.ref}}
          base: master
