name: Auto Release Tag
on: 
  pull_request:
    branches: 
      - master
    types:
      - closed
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Get branch name based on PR
      uses: andrevalentin/get-branch-name-by-pr@master
      id: pr_data
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        pr-id: ${{ github.event.pull_request.number }}
        
    - name: Print branch name
      run: |
        echo "This is PR from branch ${{ steps.pr_data.outputs.branch }}"
    
    - name: Test Check and get release version if branch name is an `release/*`
      id: get-version
      run: |
        branch="${{steps.pr_data.outputs.branch}}"
        version=$(echo ${branch} | sed -e "s/release\///g")
        is_release_branch="YES"
        if [ release/${version} == ${branch} ]; then is_release_branch="YES"; fi
        echo "::set-output name=release_version::${version}"
        echo "::set-output name=is_release_branch::${is_release_branch}"
        
    - name: Print branch name
      run: |
        echo "The branch ${{ steps.pr_data.outputs.branch }} is used for checking"
        echo "This branch has is_release_branch = ${{ steps.get-version.outputs.is_release_branch }}"
        echo "This branch has release_version = ${{ steps.get-version.outputs.release_version }}"
      
    - name: Create Release
      if: ${{ steps.get-version.outputs.is_release_branch == 'YES' }}
      id: create_release
      uses: actions/create-release@v1
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
      with:
          tag_name: ${{ steps.get-version.outputs.release_version }}
          target_commitish: master
          release_name: Release ${{ steps.get-version.outputs.release_version }}
          body: |
            Changes in this Release
            - First Change
            - Second Change
          draft: true
          prerelease: false
