name: Create production promotion pull request
on:
  push:
    branches:
      - release/2.0.0
jobs:
  AutoPRandMerged:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Reset promotion branch
        run: |
          git fetch origin master:master
          git reset --hard master
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          branch: master
          
          
