name: Auto Approve and Merge

on:
  pull_request
     branches:
       - master

jobs:
  auto-approve:
    runs-on: ubuntu-latest
    steps:
      - name: Merge approved PR
        uses: reitermarkus/automerge@v1
        with:
          token: ${{ secrets.UY_SECRET }}
          merge-method: rebase
          do-not-merge-labels: never-merge
          pull-request: ${{ github.event.pull_request.number }}
          dry-run: true
          
