name: Auto approve

on:
  pull_request:
    branches:
      - master

jobs:
  auto-approve:
    runs-on: ubuntu-latest
    steps:
      - name: Auto approves
        uses: hmarr/auto-approve-action@v2.0.0
#         if: github.actor == 'dependabot[bot]' || github.actor == 'dependabot-preview[bot]'
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"
      - name: Merge approved PR
        uses: reitermarkus/automerge@v1
        with:
          token: ${{ secrets.MY_GITHUB_TOKEN }}
          merge-method: rebase
          do-not-merge-labels: never-merge
          pull-request: ${{ github.event.pull_request.number }}
          dry-run: true
          
